### ISSUE TITLE
Slack bot messages getting cut

### ISSUE THREAD

**Issue by eranrund** [FundersClub/eng-ops#25]
![image](https://cloud.githubusercontent.com/assets/1485066/16466709/ff5c46f8-3df8-11e6-9a82-7148dc3dc37c.png)

Might be intentional but makes it a bit hard to read. A link to the issue would be nice.

**Comment by thomasrockhu** [comment]
Thanks @eranrund great suggestion

**Comment by thomasrockhu** [comment]
Rolling this into https://github.com/FundersClub/eng-ops/issues/27
