### ISSUE TITLE
Use Slack as a middleman for Zenhub integration

### ISSUE THREAD

**Issue by thomasrockhu** [FundersClub/eng-ops#26]

**Comment by chazeah** [comment]
What does that mean?

**Comment by thomasrockhu** [comment]
pulling the pipeline issue events for zen hub keeps hitting a rate limit. Emailed support and they said no plans to create webhooks. Opened an issue on their GitHub, but as a potential solution, they do have a slack integration which acts like a webhook(posts a message when something changes). May be worth using another bot to consume these messages

Thanks!
Tom

**Comment by thomasrockhu** [comment]
@chazeah https://github.com/ZenHubIO/support/issues/811

**Comment by chazeah** [comment]
Is the rate limit documented? Can we just poll less often?
