### ISSUE TITLE
Formatting for slackbot

### ISSUE THREAD

**Issue by chazeah** [FundersClub/eng-ops#27]
What you did:
- Issues you opened
- Issues you closed
- Issue assigned to you that were closed
- Issues you commented on
- PRs you opened
- PRs you closed
- PRs you commented on

Upcoming:
- Issues assigned to you in "In Progress", "Requires Followup", "New Issues", "Ready to do", "In Review"
- PRs assigned to you
- PRs you have out (you created)

Backlog
- Issues assigned to you in "Eng backlog", "Product backlog"

Example of final formatting:

```
*Recent*
• Opened #6643: <re-activation weekly>
• Closed #6641: <some other thing witl sdsdgh>
• Opened PR: <re-activation weekly>
• 4 comments on PR: <re-activation weekly>
• 1 comment on PR: <re-activation weekly>

*Upcoming*
• Work on #564: <name of issue that's assigned to you AND in In Progress, In Review>
* Ready to work on #757: <name of issue that's assigned to you AND in Ready to do>
* Follow up on #563: <name of issue that assigned to you AND in Requires Followup, New Issues>
• Review PR: <name of the PR assigned to you>
• Respond to any comments on PR: <name of PR you created>

*Backlog*
• Product backlog #546: <name of issues in Product backlog>
• Eng backlog #546: <name of issues in Eng backlog>
```

**Comment by thomasrockhu** [comment]
Fixed via https://github.com/FundersClub/eng-ops/commit/ba93ae6d39a884ef1422b281ffd749f4f31ed59c
