### ISSUE TITLE
Merged PRs erroneously appearing in Upcoming

### ISSUE THREAD

**Issue by chazeah** [FundersClub/eng-ops#28]
![image](https://cloud.githubusercontent.com/assets/899450/16531651/53501fac-3f82-11e6-8169-3a109ff11d54.png)
https://github.com/FundersClub/FundersClub/issues/6671

Not sure why it was appearing for me.

**Comment by thomasrockhu** [comment]
Should be fixed, I think it was an issue with syncing not happening
