### ISSUE TITLE
Make slackbot send a weekly report

### ISSUE THREAD

**Issue by j-friedman** [FundersClub/eng-ops#31]
Thoughts about what to send:
- Total number of story points from closed issues
- Summary of all of the closed tickets since the last report
- ???

**Comment by thomasrockhu** [comment]
Team accomplishments
- Opened {#} of issues (avg = {#}, last_week = {#})
- Closed {#} of issues (avg = {#}, last_week = {#})
- Completed {#} points (avg = {#}, last_week = {#})
- Issue breakdown
  > {#. %} Bug
  > {#, %} Enhancement
  > ...

Personal report
- Opened {#} of issues (avg = {#}, last_week = {#})
- Closed {#} of issues (avg = {#}, last_week = {#})
- Completed {#} points (avg = {#}, last_week = {#})
- Issue breakdown
  > {#. %} Bug
  > {#, %} Enhancement
  > ...

**Comment by thomasrockhu** [comment]
Fixed via https://github.com/FundersClub/eng-ops/commit/509ff53339041f4af8f64aeafab3b326e5931f2d
