### ISSUE TITLE
Minor formatting ish

### ISSUE THREAD

**Issue by chazeah** [FundersClub/eng-ops#34]
![image](https://cloud.githubusercontent.com/assets/899450/16743236/37c72a9c-4760-11e6-8169-fe34b3873d13.png)
1. There's a blank message after the "Recent" message. (highlighted gray above)
2. There's extra whitespace below the "Upcoming" header

**Comment by thomasrockhu** [comment]
@chazeah what day was that message sent?  The issue with the blank space was fixed recently

**Comment by thomasrockhu** [comment]
actually doesn't matter, was a totally different issue

fixed via https://github.com/FundersClub/eng-ops/commit/d3af1f73dd639ff2cf4a7db56b461553adb290c7
