### ISSUE TITLE
Naive datetimes are used in a bunch of places

### ISSUE THREAD

**Issue by j-friedman** [FundersClub/eng-ops#39]
There's a lot of `import datetime` .... `datetime.now()`. This should all be replaced with h`from django.utils import timezone` and `timezone.now()`, respectively.

**Comment by thomasrockhu** [comment]
@eranrund @chazeah going to assign to @k unless you have any qualms

**Comment by j-friedman** [comment]
@k these changes look fine but they're not in `master` and there's no PR for them. If you open one you've got an LGTM from me

**Comment by j-friedman** [comment]
or you could just stick them into `master` directly, I guess.
