### ISSUE TITLE
github_callback must check that requests are actually coming from github

### ISSUE THREAD

**Issue by j-friedman** [FundersClub/eng-ops#40]
We need to check for more than just the presence of `HTTP_X_GITHUB_EVENT`. 

https://developer.github.com/webhooks/securing/#validating-payloads-from-github

**Comment by ngnmnfn** [comment]
TEST COMMENT!

**Comment by ngnmnfn** [comment]
MORE TEST COMMENTS!

**Comment by ngnmnfn** [comment]
test comment

**Comment by ngnmnfn** [comment]
test

**Comment by ngnmnfn** [comment]
test

**Comment by ngnmnfn** [comment]
tesst

**Comment by j-friedman** [comment]
another test

**Comment by j-friedman** [comment]
I made a support request to Heroku because it seems like the `X-Hub-Signature` header is being stripped out - it's not in `request` by the time it reaches our view.

> Hi there,
> 
> Our application here provides a webhook endpoint for github, and I was adding signature verification support to it when I discovered that the X-Hub-Signature header is being stripped out somewhere before the request is reaching our view. I've verified that github is actually sending it, and when I run heroku local it is actually part of the request, as well. Is there a possibility that something on your end is stripping it out?
> 
> For what it's worth, other custom headers like X-Github-Event are not being removed.
> 
> Thanks!
> Jon

**Comment by j-friedman** [comment]
Heroku's response:

> Hi Jon,
> 
> We're actually using the header for all customer interactions with GitHub for our review apps product, I took a look at the code and we're accessing it via:
> 
> `@signature ||= request.env['HTTP_X_HUB_SIGNATURE']`
> So I can say with some certainty we're not dropping this header.
> 
> Regards,
> John.

Soooo.... yeah.

**Comment by eranrund** [comment]
test

**Comment by eranrund** [comment]
So now that we figured why this header wasn't showing up, who's going to do something with it? @moofive @thomasrockhu

**Comment by j-friedman** [comment]
@eranrund I can do it
