### ISSUE TITLE
Combine Closed/Commented with they're on same issue

### ISSUE THREAD

**Issue by chazeah** [FundersClub/eng-ops#41]
Unnecessary to have an issue appear twice as two different line items:
![image](https://cloud.githubusercontent.com/assets/899450/16884746/f448c8f2-4a7f-11e6-8e0d-664c4c2b751a.png)

Ideal would be something like
"Closed and commented on #6880: ..."

**Comment by thomasrockhu** [comment]
Fixed via https://github.com/FundersClub/eng-ops/commit/22a942f927198d197fa7feacd395e271e5fa40bf

**Comment by thomasrockhu** [comment]
Not fixed

**Comment by thomasrockhu** [comment]
this SHOULD be fixed
