### ISSUE TITLE
Blank entries in message

### ISSUE THREAD

**Issue by chazeah** [FundersClub/eng-ops#46]
![image](https://cloud.githubusercontent.com/assets/899450/17188174/d35c378a-53f0-11e6-922c-d155df4f8332.png)

These point to:
https://github.com/FundersClub/FundersClub/pull/7051
https://github.com/FundersClub/FundersClub/pull/6986
https://github.com/FundersClub/FundersClub/pull/7011
https://github.com/FundersClub/fundersclub-operations/pull/401

Not urgent, just FYI.

**Comment by chazeah** [comment]
Let me know if you help repro-ing:
![image](https://cloud.githubusercontent.com/assets/899450/17305686/6bfb245e-57e0-11e6-8267-0f8592cffe14.png)

**Comment by thomasrockhu** [comment]
no worries @chazeah I'm getting it too

**Comment by thomasrockhu** [comment]
fixed via https://github.com/FundersClub/eng-ops/commit/07087abc6cabda9a5b2014b59e05a89db50a881b
