### ISSUE TITLE
Expand explaination in comment

### ISSUE THREAD

**Issue by j-friedman** [FundersClub/eng-ops#47]
In `api.tasks` there is this function definition:

``` python
def sync_issues():
    minute = datetime.now().minute / 10
    issues = Issue.objects.filter(closed_at__isnull=True)
    for issue in issues:
        #  Hack because Zenhub API
        if issue.id % 6 == minute:
            _sync_issue(issue)
```

Could you explain what's up with the hack?

**Comment by thomasrockhu** [comment]
> because Zenhub API

but yeah, I'll add more details

**Comment by thomasrockhu** [comment]
Fixed via https://github.com/FundersClub/eng-ops/commit/508e62a526c38a22d1157e823b563e42da9c5b46
