### ISSUE TITLE
Closed tickets should have date of closure

### ISSUE THREAD

**Issue by j-friedman** [FundersClub/eng-ops#53]
Standup bot should tell up when a ticket got closed. Just a MM/DD sort of thing. It'd be convenient.

**Comment by thomasrockhu** [comment]
@moofive Confused, as the standup bot shows tickets that got closed int he past 24 hours only

**Comment by thomasrockhu** [comment]
bump @moofive

**Comment by j-friedman** [comment]
In that case, never mind.
