### ISSUE TITLE
Allow me to unsubscribe from daily updates sent by the bot

### ISSUE THREAD

**Issue by eranrund** [FundersClub/eng-ops#82]
Please :)

**Comment by thomasrockhu** [comment]
fixed via https://github.com/FundersClub/eng-ops/commit/60a4de43cfbd0df171f2895baa7d34f7d05231f1

@eranrund I also unsubscribed you

**Comment by eranrund** [comment]
Thanks. Would I still be getting the weekly summaries (team and self)?

**Comment by thomasrockhu** [comment]
yup!
